// comment
pipeline {
	agent none
	stages {
		stage("Example ${variable}") {
			steps {
				echo 'Hello, Maven'
				sh 'mvn --version'
			}
			
		}
		stage('Example Test') {
			agent { docker 'openjdk:17-jre'}
			steps {
				echo "Hello, $JDK"
				sh 'java --version'
			}
		}
	}
	post {
		always {
			echo 'I will always say Hello again!'
		}
	}
}

def func() {
	// todo
}
